#!/bin/bash
if [ ! -f $OPENSHIFT_DATA_DIR/last_run ]; then
    touch $OPENSHIFT_DATA_DIR/last_run
fi
if [[ $(find $OPENSHIFT_DATA_DIR/last_run -mmin +4) ]]; then #run every 5 mins
    rm -f $OPENSHIFT_DATA_DIR/last_run
    touch $OPENSHIFT_DATA_DIR/last_run
    # The command(s) that you want to run every 5 minutes
    cd ${OPENSHIFT_REPO_DIR}/
    nohup python job.py 2>&1 >> ${OPENSHIFT_LOG_DIR}/job.log &
fi
